name: Deploy to GitHub pages

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate storybook
        run: |
          npm ci
          npm run build-storybook
      - name: Init new repo in dist folder and commit generated files
        run: |
          cd storybook-static
          git init
          git add -A
          git config --local user.email ${{secrets.gh_user_mail}}
          git config --local user.name ${{secrets.gh_user_name}}
          git commit -m 'deploy'
